APP_NAME = "Manual Data Ingest"
APP_DATABASE = "DEMO_DWH"
APP_SCHEMA = "STREAMLIT_APP"
MART_SCHEMA = "RETAIL_MART"
FORECAST_TABLE = "FORECAST"
ADMIN_ROLE = "STREAMLIT_APP_ADMIN"
ACCOUNTADMIN_IS_ADMIN = True
SOURCE_APP = "MANUAL_DATA_INGEST"
ENABLE_FOREIGN_KEY_VALIDATION = False

PENDING_STATUS = "PENDING_APPROVAL"
APPROVED_STATUS = "APPROVED"
REJECTED_STATUS = "REJECTED"

FORECAST_TABLE_NAME = f"{APP_DATABASE}.{APP_SCHEMA}.{FORECAST_TABLE}"
FORECAST_KEY_COLUMN = "FORECAST_KEY"
REQUIRED_TABLES = {FORECAST_TABLE}

EXPECTED_FORECAST_FIELDS = {
    "FORECAST_GRAIN_KEY",
    "FORECAST_CODE",
    "DATE_KEY",
    "PERIOD_START_DATE_KEY",
    "PERIOD_END_DATE_KEY",
    "PRODUCT_KEY",
    "STORE_KEY",
    "CHANNEL_KEY",
    "SKU",
    "COUNTRY_CODE",
    "FORECAST_QUANTITY",
    "COMMENT",
    "STATUS",
}

REQUIRED_FORECAST_FIELDS = {
    "FORECAST_GRAIN_KEY",
    "FORECAST_CODE",
    "DATE_KEY",
    "PERIOD_START_DATE_KEY",
    "PERIOD_END_DATE_KEY",
    "PRODUCT_KEY",
    "STORE_KEY",
    "CHANNEL_KEY",
    "SKU",
    "COUNTRY_CODE",
    "FORECAST_QUANTITY",
    "STATUS",
}

DATE_KEY_FIELDS = {
    "DATE_KEY",
    "PERIOD_START_DATE_KEY",
    "PERIOD_END_DATE_KEY",
}
